sudo: required
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_2abe52d3bdc8_key -iv $encrypted_2abe52d3bdc8_iv -in scaleway.enc -out /swarm.key -d
- chmod 600 /swarm.key
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
- sudo service docker stop
- sudo apt-cache madison docker-ce
- sudo apt-get install docker-ce=17.11.0~ce-0~ubuntu
- docker version
script:
- chmod -R +x ./scripts
- "./scripts/travis-deploy.sh"
