version: '2.0'

services:
  docker-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_REMOTE_HOST: c591f781-f84c-4734-9910-4ef92662f736.pub.cloud.scaleway.com
      DEPLOY_USER: root
    volumes:
      - ./swarm.key:/swarm.key
