version: '3.3'

networks:
  frontend:
  backend:

services:

  traefik:
    image: traefik
    command:
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --defaultEntryPoints=http
      - --entrypoints=Name:http Address::80
      - --web
    networks:
      - frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 100M
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: jwilder/whoami
    networks:
      - frontend
    deploy:
      labels:
        traefik.frontend.rule: "Host:4ac95ec0-0b28-4be0-8a7b-298fbbcb5998.pub.cloud.scaleway.com"
        traefik.port: "8000"
        traefik.docker.network: "cumulocity_production_frontend"
      replicas: 4

  appsample:
    image: ffaerber/appsample
    networks:
      - frontend
      - backend
    environment:
      MONGO_HOST: mongodb://mongo-db/test
    deploy:
      labels:
        traefik.frontend.rule: "Host:4ac95ec0-0b28-4be0-8a7b-298fbbcb5998.pub.cloud.scaleway.com;PathPrefixStrip:/appsample"
        traefik.port: "3000"
        traefik.docker.network: "cumulocity_production_frontend"
      replicas: 30

  mongo-db:
    networks:
      - backend
    image: mongo
